/*
 * DC_MOTOR_prg.c
 *
 *  Created on: Dec 8, 2022
 *      Author: hp
 */
#include "../../LIB/STD_TYPES.h"
#include "../../LIB/BIT_MATH.h"

#include "../../MCAL/DIO/DIO_int.h"

#include "DC_MOTOR_cfg.h"
#include "DC_MOTOR_int.h"

void DC_MOTOR_vInt()
{
	DIO_vPinDir(DC_MOTOR1_PORT,DC_MOTOR1_PIN1,DIR_OUTPUT);
	DIO_vPinDir(DC_MOTOR1_PORT,DC_MOTOR1_PIN2,DIR_OUTPUT);
	DIO_vPinDir(DC_MOTOR2_PORT,DC_MOTOR2_PIN1,DIR_OUTPUT);
	DIO_vPinDir(DC_MOTOR2_PORT,DC_MOTOR2_PIN2,DIR_OUTPUT);
}

void forward()
{
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN1,VAL_HIGH);
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN2,VAL_LOW);
	DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN1,VAL_HIGH);
	DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN2,VAL_LOW);
}

void Rotate()
{
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN1,VAL_HIGH);
		DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN2,VAL_LOW);
		DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN1,VAL_LOW);
		DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN2,VAL_LOW);
}

void right()
{
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN1,VAL_HIGH);
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN2,VAL_LOW);
	DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN1,VAL_LOW);
	DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN2,VAL_HIGH);

}

void left()
{
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN1,VAL_LOW);
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN2,VAL_HIGH);
	DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN1,VAL_HIGH);
	DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN2,VAL_LOW);
}

void stop()
{
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN1,VAL_LOW);
	DIO_vSetPinVal(DC_MOTOR1_PORT,DC_MOTOR1_PIN2,VAL_LOW);
	DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN1,VAL_LOW);
	DIO_vSetPinVal(DC_MOTOR2_PORT,DC_MOTOR2_PIN2,VAL_LOW);
}

void DC_MOTOR_Control(u8 A_u8Motor_Port,u8 A_u8Motor_Pin, u8 A_u8Value)
{
	DIO_vSetPinVal(A_u8Motor_Port,A_u8Motor_Pin,A_u8Value);
}
