/*
 * ULTRASONIC_cfg.h
 *
 *  Created on: Nov 25, 2022
 *      Author: hp
 */

#ifndef ULTRASONIC_ULTRASONIC_CFG_H_
#define ULTRASONIC_ULTRASONIC_CFG_H_

/*Center*/
#define   ULTRASONIC_TRIGER_PORT_C   PORTA_ID
#define   ULTRASONIC_ECHO_PORT_C     PORTA_ID
#define   ULTRASONIC_TRIGER_PIN_C    PIN1_ID
#define   ULTRASONIC_ECHO_PIN_C      PIN4_ID

/*Left*/
#define   ULTRASONIC_TRIGER_PORT_L   PORTD_ID
#define   ULTRASONIC_ECHO_PORT_L     PORTD_ID
#define   ULTRASONIC_TRIGER_PIN_L    PIN6_ID
#define   ULTRASONIC_ECHO_PIN_L      PIN7_ID

/*Right*/
#define   ULTRASONIC_TRIGER_PORT_R   PORTA_ID
#define   ULTRASONIC_ECHO_PORT_R     PORTA_ID
#define   ULTRASONIC_TRIGER_PIN_R    PIN2_ID
#define   ULTRASONIC_ECHO_PIN_R      PIN5_ID

#endif /* ULTRASONIC_ULTRASONIC_CFG_H_ */
