/*
 * TIMER2_cfg.h
 *
 *  Created on: Sep 13, 2022
 *      Author: mostafa_ebrahim
 */

#ifndef MCAL_TIMER2_TIMER2_CFG_H_
#define MCAL_TIMER2_TIMER2_CFG_H_


/*options of Timer2 Mode:
 * TIMER2_NORMAL_MODE
 * TIMER2_PWM_PHASE_CORRECT_MODE
 * TIMER2_CTC_MODE
 * TIMER2_FAST_PWM_MODE
 * */
#define TIMER2_MODE TIMER2_FAST_PWM_MODE

/*options of TIMER2 Clock Select:
*TIMER2_NO_CLK
*TIMER2_NO_PRESCALER
*TIMER2_8_PRESCALER
*TIMER2_32_PRESCALER
*TIMER2_64_PRESCALER
*TIMER2_128_PRESCALER
*TIMER2_256_PRESCALER
*TIMER2_1024_PRESCALER
**/
#define TIMER2_CLOCK_SELECT TIMER2_256_PRESCALER

/*OC2 pin option CTC
 * TIMER2_OC2_DISCONNECTED
 * TIMER2_OC2_TOGGLE
 * TIMER2_OC2_CLR
 * TIMER2_OC2_SET
 *
 * */
#define TIMER2_OCP_PIN_MODE TIMER2_OC2_SET

/* interrupt state
 *
 * Options:
 * 1- TIMER2_INT_ENABLE
 * 2- TIMER2_INT_DISABLE
 * */
#define TIMER2_INTERRUPT_STATE_OVF TIMER2_INT_ENABLE
#define TIMER2_INTERRUPT_STATE_CTC TIMER2_INT_DISABLE


/* TIMER0 FCPU frequency
 *
 *	Options:
 *	user specify the frequency
 * */
#define TIMER2_InputFreq 8000000UL


/*PWM Mode Options:
 * TIMER2_PWM_NON_INVERTING
 * TIMER2_PWM_INVERTING
 * NOTE:
 * NON_INVERTING:Duty Cycle->OCR
 * INVERTING:Duty Cycle ~OCR*/
#define TIMER2_PWM_MODE TIMER2_PWM_NON_INVERTING

/* OC2 Pin Configuration */
#define OC2_PORT PORTD_ID
#define OC2_PIN	 PIN7_ID



#endif /* MCAL_TIMER2_TIMER2_CFG_H_ */
